Imports and Packages

In [ ]:
import pandas as pd

In [ ]:
pip install fancyimpute

In [ ]:
from fancyimpute import KNN

Reading Data and Checking Columns of Missing Values

In [ ]:
data = pd.read_excel('cairo_final_usethis_6.xlsx')

In [ ]:
# data cleaning for grade column
grade_mapping = {'Low': 1, 'Intermediate': 2, 'High': 3}
data['Grade'] = data['Grade'].replace(grade_mapping)
data.Grade

0      3.0
1      1.0
2      2.0
3      2.0
4      NaN
      ...
750    1.0
751    2.0
752    2.0
753    3.0
754    2.0
Name: Grade, Length: 755, dtype: float64

In [ ]:
columns_to_remove = ['MRN', 'Birth.Date', 'First_BMI','Date.of.Diagnosis','Tumor size','Tumor size trim','Tumor_size_cm2','KI67%','Positive.LN','Total.LN.Dissected']

In [ ]:
categorical_data = data.drop(columns=columns_to_remove)
categorical_data

,Residencey,DM,HTN,VTE,CVD,Others,F.Hx.of.BC,Menopausal.state,Hormonal.Contraception,Lactation,...,Laterality,ER,PR,HER2,Unilateral.Bilateral,Site,Tumor.Type,Grade,Surgery.Type,Axilla.Specimen.Type
0,Giza,No,Yes,No,No,No,Yes - BC,Post-M,NaN,NaN,...,Right,Positive,Positive,Negative,Unilateral,Lower outer quadrant,Invasive duct carcinoma (NST),3.0,Conservative,NaN
1,Cairo,No,No,No,No,No,Yes - BC,Pre-M,NaN,NaN,...,Right,Positive,Positive,Negative,Unilateral,Upper outer quadrant,Invasive duct carcinoma (NST),1.0,Conservative,Sentinel Lymph Node Biopsy (SLNB)
2,Cairo,Yes,Yes,No,No,No,No,Post-M,NaN,NaN,...,Left,Positive,Positive,Positive,Unilateral,Upper outer quadrant,Invasive duct carcinoma (NST),2.0,Mastectomy,Axillary Dissection (ALND)
3,Cairo,No,No,No,No,No,No,Pre-M,NaN,NaN,...,Left,Positive,Positive,Negative,Unilateral,Multifocal,Invasive duct carcinoma (NST),2.0,Mastectomy,NaN
4,Giza,Yes,No,No,No,No,No,Post-M,NaN,NaN,...,Right,Positive,Positive,Negative,Unilateral,NaN,"Ductal carcinoma in situ, DCIS",NaN,Conservative,Sentinel Lymph Node Biopsy (SLNB)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750,Giza,No,Yes,No,No,No,No,Pre-M,Yes,No,...,Right,Positive,Positive,Negative,Unilateral,Upper outer quadrant,Invasive duct carcinoma (NST),1.0,Conservative,Sentinel Lymph Node Biopsy (SLNB)
751,Giza,No,No,No,No,No,Yes - BC,Post-M,Yes,No,...,Right,Positive,Positive,Negative,Unilateral,12 O'Clock,Invasive duct carcinoma (NST),2.0,Conservative,Sentinel Lymph Node Biopsy (SLNB)
752,Giza,No,No,No,No,No,No,Post-M,Yes,No,...,Right,Positive,Positive,Negative,Unilateral,Upper outer quadrant,Invasive duct carcinoma (NST),2.0,Conservative,Axillary Clearance
753,Cairo,No,No,No,No,No,Yes - BC,Pre-M,Yes,No,...,Left,Negative,Positive,Negative,Unilateral,Upper inner quadrant,Invasive duct carcinoma (NST),3.0,Conservative,Sentinel Lymph Node Biopsy (SLNB)
754,Giza,No,Yes,No,No,No,Yes - other cancers,Pre-M,Yes,No,...,Right,Positive,Positive,Negative,Unilateral,Upper inner quadrant,Invasive duct carcinoma (NST),2.0,Mastectomy,Sentinel Lymph Node Biopsy (SLNB)

In [ ]:
# checking columns that have missing values or NULL or Unrecorded
missing_values = categorical_data.isnull().sum()
null_values = (categorical_data == "NULL").sum()
unrecorded_values = (categorical_data == "Unrecorded").sum()
missing_data=missing_values+unrecorded_values+null_values
missing_columns = missing_data[missing_data > 0]
print("Columns with missing values or 'NULL':")
print(missing_columns)

Columns with missing values or 'NULL':
Residencey                   7
DM                          18
HTN                         18
VTE                         18
CVD                         18
Others                     212
F.Hx.of.BC                  36
Menopausal.state             9
Hormonal.Contraception     216
Lactation                  285
Lymphovascular.Invasion    666
PR                           1
Unilateral.Bilateral         1
Site                        28
Tumor.Type                   9
Grade                       37
Surgery.Type                 7
Axilla.Specimen.Type       153
dtype: int64

In [ ]:
categorical_data_missing=categorical_data[missing_columns.index]
categorical_data_missing_before_filling=categorical_data[missing_columns.index]
categorical_data_missing # Categorical Data Before Imputation

,Residencey,DM,HTN,VTE,CVD,Others,F.Hx.of.BC,Menopausal.state,Hormonal.Contraception,Lactation,Lymphovascular.Invasion,PR,Unilateral.Bilateral,Site,Tumor.Type,Grade,Surgery.Type,Axilla.Specimen.Type
0,Giza,No,Yes,No,No,No,Yes - BC,Post-M,NaN,NaN,NaN,Positive,Unilateral,Lower outer quadrant,Invasive duct carcinoma (NST),3.0,Conservative,NaN
1,Cairo,No,No,No,No,No,Yes - BC,Pre-M,NaN,NaN,NaN,Positive,Unilateral,Upper outer quadrant,Invasive duct carcinoma (NST),1.0,Conservative,Sentinel Lymph Node Biopsy (SLNB)
2,Cairo,Yes,Yes,No,No,No,No,Post-M,NaN,NaN,NaN,Positive,Unilateral,Upper outer quadrant,Invasive duct carcinoma (NST),2.0,Mastectomy,Axillary Dissection (ALND)
3,Cairo,No,No,No,No,No,No,Pre-M,NaN,NaN,NaN,Positive,Unilateral,Multifocal,Invasive duct carcinoma (NST),2.0,Mastectomy,NaN
4,Giza,Yes,No,No,No,No,No,Post-M,NaN,NaN,NaN,Positive,Unilateral,NaN,"Ductal carcinoma in situ, DCIS",NaN,Conservative,Sentinel Lymph Node Biopsy (SLNB)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750,Giza,No,Yes,No,No,No,No,Pre-M,Yes,No,NaN,Positive,Unilateral,Upper outer quadrant,Invasive duct carcinoma (NST),1.0,Conservative,Sentinel Lymph Node Biopsy (SLNB)
751,Giza,No,No,No,No,No,Yes - BC,Post-M,Yes,No,NaN,Positive,Unilateral,12 O'Clock,Invasive duct carcinoma (NST),2.0,Conservative,Sentinel Lymph Node Biopsy (SLNB)
752,Giza,No,No,No,No,No,No,Post-M,Yes,No,NaN,Positive,Unilateral,Upper outer quadrant,Invasive duct carcinoma (NST),2.0,Conservative,Axillary Clearance
753,Cairo,No,No,No,No,No,Yes - BC,Pre-M,Yes,No,NaN,Positive,Unilateral,Upper inner quadrant,Invasive duct carcinoma (NST),3.0,Conservative,Sentinel Lymph Node Biopsy (SLNB)
754,Giza,No,Yes,No,No,No,Yes - other cancers,Pre-M,Yes,No,NaN,Positive,Unilateral,Upper inner quadrant,Invasive duct carcinoma (NST),2.0,Mastectomy,Sentinel Lymph Node Biopsy (SLNB)

Mode Imputation For Categorical Data

In [ ]:
#Computing the mode for each column:
mode_values = categorical_data_missing.mode().iloc[0]
mode_values

In [ ]:
#Data Imputation using Mode for Missing Values:
for column in categorical_data_missing.columns:
      categorical_data_missing[column].fillna(mode_values[column], inplace=True)

<ipython-input-9-47b6f7f13f48>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  categorical_data_missing[column].fillna(mode_values[column], inplace=True)

In [ ]:
categorical_data_missing.head() #Categorical Data after imputation of missing cells

,Residencey,DM,HTN,VTE,CVD,Others,F.Hx.of.BC,Menopausal.state,Hormonal.Contraception,Lactation,Lymphovascular.Invasion,PR,Unilateral.Bilateral,Site,Tumor.Type,Grade,Surgery.Type,Axilla.Specimen.Type
0,Giza,No,Yes,No,No,No,Yes - BC,Post-M,No,No,No,Positive,Unilateral,Lower outer quadrant,Invasive duct carcinoma (NST),3.0,Conservative,Sentinel Lymph Node Biopsy (SLNB)
1,Cairo,No,No,No,No,No,Yes - BC,Pre-M,No,No,No,Positive,Unilateral,Upper outer quadrant,Invasive duct carcinoma (NST),1.0,Conservative,Sentinel Lymph Node Biopsy (SLNB)
2,Cairo,Yes,Yes,No,No,No,No,Post-M,No,No,No,Positive,Unilateral,Upper outer quadrant,Invasive duct carcinoma (NST),2.0,Mastectomy,Axillary Dissection (ALND)
3,Cairo,No,No,No,No,No,No,Pre-M,No,No,No,Positive,Unilateral,Multifocal,Invasive duct carcinoma (NST),2.0,Mastectomy,Sentinel Lymph Node Biopsy (SLNB)
4,Giza,Yes,No,No,No,No,No,Post-M,No,No,No,Positive,Unilateral,Upper outer quadrant,"Ductal carcinoma in situ, DCIS",2.0,Conservative,Sentinel Lymph Node Biopsy (SLNB)

In [ ]:
# checking columns that have missing values or NULL or Unrecorded
missing_values2 = categorical_data_missing.isnull().sum()
null_values2 = (categorical_data_missing == "NULL").sum()
unrecorded_values2 = (categorical_data_missing == "Unrecorded").sum()
missing_data2=missing_values2+unrecorded_values2+null_values2
missing_columns2 = missing_data2[missing_data2 > 0]
print("Columns with missing values or 'NULL' or 'Unrecorded':")
print(missing_columns2)

Columns with missing values or 'NULL' or 'Unrecorded':
DM                  11
HTN                 11
VTE                 11
CVD                 11
F.Hx.of.BC          17
Menopausal.state     1
dtype: int64

In [ ]:
#Replacing unrecorded values in columns withs its mode:
categorical_data_missing['DM'].replace("Unrecorded", "No", inplace=True)
categorical_data_missing['HTN'].replace("Unrecorded", "No", inplace=True)
categorical_data_missing['VTE'].replace("Unrecorded", "No", inplace=True)
categorical_data_missing['CVD'].replace("Unrecorded", "No", inplace=True)
categorical_data_missing['F.Hx.of.BC'].replace("Unrecorded", "No", inplace=True)
categorical_data_missing['Menopausal.state'].replace("Unrecorded", "Post-M", inplace=True)

In [ ]:
categorical_data_missing #categorical data after filling missing values and unrecorded values

MICE  Imputer For Categorical Data

In [ ]:
categorical_data2 = data.drop(columns=columns_to_remove)
categorical_data_missing2=categorical_data2[missing_columns.index]
categorical_data_missing2

In [ ]:
categorical_data_encoded = pd.get_dummies(categorical_data_missing2)
categorical_data_encoded

In [ ]:
from sklearn.impute import IterativeImputer

In [ ]:
imputer = IterativeImputer(max_iter=10, random_state=0)
imputed_data = imputer.fit_transform(categorical_data_encoded)

In [ ]:
categorical_imputed = pd.DataFrame(imputed_data, columns=categorical_data_encoded.columns)

In [ ]:
categorical_imputed

,Grade,Residencey_Alexandria,Residencey_Assiutآ,Residencey_Beheiraآ,Residencey_Beni Suef,Residencey_Cairo,Residencey_Dakahlia,Residencey_Fayoum,Residencey_Gharbia,Residencey_Giza,...,Tumor.Type_Tubular carcinoma,Surgery.Type_Conservative,Surgery.Type_Mastectomy,Axilla.Specimen.Type_Axillary Clearance,Axilla.Specimen.Type_Axillary Dissection (ALND),Axilla.Specimen.Type_Axillary Evacuation,Axilla.Specimen.Type_Axillary Lymph Node Sampling,Axilla.Specimen.Type_Non-Sentinel Lymph Node Biopsy (Non-SLNB),Axilla.Specimen.Type_SLNB & Non-SLNB,Axilla.Specimen.Type_Sentinel Lymph Node Biopsy (SLNB)
0,3.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.000000,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,2.000000,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,2.000000,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2.099154,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750,1.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
751,2.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
752,2.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
753,3.000000,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
754,2.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

RF Data Imputation

In [ ]:
categorical_data3 = data.drop(columns=columns_to_remove)
categorical_data_missing3=categorical_data3[missing_columns.index]
categorical_data_missing3

,Residencey,DM,HTN,VTE,CVD,Others,F.Hx.of.BC,Menopausal.state,Hormonal.Contraception,Lactation,Lymphovascular.Invasion,PR,Unilateral.Bilateral,Site,Tumor.Type,Grade,Surgery.Type,Axilla.Specimen.Type
0,Giza,No,Yes,No,No,No,Yes - BC,Post-M,NaN,NaN,NaN,Positive,Unilateral,Lower outer quadrant,Invasive duct carcinoma (NST),3.0,Conservative,NaN
1,Cairo,No,No,No,No,No,Yes - BC,Pre-M,NaN,NaN,NaN,Positive,Unilateral,Upper outer quadrant,Invasive duct carcinoma (NST),1.0,Conservative,Sentinel Lymph Node Biopsy (SLNB)
2,Cairo,Yes,Yes,No,No,No,No,Post-M,NaN,NaN,NaN,Positive,Unilateral,Upper outer quadrant,Invasive duct carcinoma (NST),2.0,Mastectomy,Axillary Dissection (ALND)
3,Cairo,No,No,No,No,No,No,Pre-M,NaN,NaN,NaN,Positive,Unilateral,Multifocal,Invasive duct carcinoma (NST),2.0,Mastectomy,NaN
4,Giza,Yes,No,No,No,No,No,Post-M,NaN,NaN,NaN,Positive,Unilateral,NaN,"Ductal carcinoma in situ, DCIS",NaN,Conservative,Sentinel Lymph Node Biopsy (SLNB)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750,Giza,No,Yes,No,No,No,No,Pre-M,Yes,No,NaN,Positive,Unilateral,Upper outer quadrant,Invasive duct carcinoma (NST),1.0,Conservative,Sentinel Lymph Node Biopsy (SLNB)
751,Giza,No,No,No,No,No,Yes - BC,Post-M,Yes,No,NaN,Positive,Unilateral,12 O'Clock,Invasive duct carcinoma (NST),2.0,Conservative,Sentinel Lymph Node Biopsy (SLNB)
752,Giza,No,No,No,No,No,No,Post-M,Yes,No,NaN,Positive,Unilateral,Upper outer quadrant,Invasive duct carcinoma (NST),2.0,Conservative,Axillary Clearance
753,Cairo,No,No,No,No,No,Yes - BC,Pre-M,Yes,No,NaN,Positive,Unilateral,Upper inner quadrant,Invasive duct carcinoma (NST),3.0,Conservative,Sentinel Lymph Node Biopsy (SLNB)
754,Giza,No,Yes,No,No,No,Yes - other cancers,Pre-M,Yes,No,NaN,Positive,Unilateral,Upper inner quadrant,Invasive duct carcinoma (NST),2.0,Mastectomy,Sentinel Lymph Node Biopsy (SLNB)